name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Clean dist directory
        run: rm -rf dist

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Copy package.json to dist
        run: cp package.json dist/

      - name: Copy README.md to dist
        run: cp README.md dist/

      - name: Update version in dist/package.json
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          jq --arg version "$TAG_VERSION" '.version = $version' dist/package.json > dist/package.json.tmp && mv dist/package.json.tmp dist/package.json

      - name: Authenticate to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: |
          cd dist
          for i in {1..5}; do
            npm publish && break || sleep 30
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
